In [ ]:
!pip install spacy

In [ ]:
!python -m spacy download en_core_web_lg

In [ ]:
!pip install nltk

In [ ]:
!pip install ipywidgets

In [14]:
import nltk

nltk.download('wordnet')
nltk.download('omw-1.4')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...


True

In [ ]:
!pip install openai

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 44.9/44.9 kB 2.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 242.1/242.1 kB 11.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 148.2/148.2 kB 8.2 MB/s eta 0:00:00
  Created wheel for openai: filename=openai-0.25.0-py3-none-any.whl size=55859 sha256=92706d6e1efdda0d7a05877f9e54e5e73d54822cf2a1784e9c6e59cfd6ab363c
  Stored in directory: /home/codespace/.cache/pip/wheels/b4/2b/95/737049113f1905133261431692b68dda34fadb3022700a4187
Successfully built openai


In [ ]:
import spacy

nlp = spacy.load("en_core_web_lg")

In [ ]:
api_key = "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"
openai.api_key = api_key

In [10]:
# symptom synonym dataset - from data-loader.ipynb
sympsyn = [('https://ontology.drpawspaw.com/ADSO0000000059', 'Bloated Tummy', []),
 ('https://ontology.drpawspaw.com/ADSO0000000065', 'Unusual Collapse', []),
 ('https://ontology.drpawspaw.com/ADSO0000000048', 'Swelling Limbs', []),
 ('https://ontology.drpawspaw.com/ADSO0000000007', 'coughing', []),
 ('https://ontology.drpawspaw.com/ADSO0000000045', 'Weight Loss', []),
 ('https://ontology.drpawspaw.com/ADSO0000000027', 'Eye Discharge', []),
 ('https://ontology.drpawspaw.com/ADSO0000000008', 'Vomiting', []),
 ('https://ontology.drpawspaw.com/ADSO0000000078', 'Thickening of Skin', []),
 ('https://ontology.drpawspaw.com/ADSO0000000005', 'Fever', []),
 ('https://ontology.drpawspaw.com/ADSO0000000034', 'Muscle Twitching', []),
 ('https://ontology.drpawspaw.com/ADSO0000000057', 'Nausea', []),
 ('https://ontology.drpawspaw.com/ADSO0000000016', 'Blood Diarrhea', []),
 ('https://ontology.drpawspaw.com/ADSO0000000070', 'Kidney Disease', []),
 ('https://ontology.drpawspaw.com/ADSO0000000082', 'Fast Breathing', []),
 ('https://ontology.drpawspaw.com/ADSO0000000038',
  'Involuntary Eye Movements',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000097', 'Dark Discharge', []),
 ('https://ontology.drpawspaw.com/ADSO0000000076', 'Pigmentation of Skin', []),
 ('https://ontology.drpawspaw.com/ADSO0000000075',
  'Bumps on Skin',
  ['Papules']),
 ('https://ontology.drpawspaw.com/ADSO0000000029',
  'Scratching Ears',
  ['Crusting in the Ears']),
 ('https://ontology.drpawspaw.com/ADSO0000000040', 'Seizures', []),
 ('https://ontology.drpawspaw.com/ADSO0000000017', 'Lethargy', ['Low Energy']),
 ('https://ontology.drpawspaw.com/ADSO0000000006',
  'Inflammation of Joints',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000050', 'Whining', []),
 ('https://ontology.drpawspaw.com/ADSO0000000100',
  'Swelling of Ear Canals',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000023', 'Pain', []),
 ('https://ontology.drpawspaw.com/ADSO0000000053',
  'Severe Weight Loss',
  ['Reduce body Weight']),
 ('https://ontology.drpawspaw.com/ADSO0000000018', 'Anorexia', []),
 ('https://ontology.drpawspaw.com/ADSO0000000081',
  'Jaundiced Skin',
  ['Yellow Skin']),
 ('https://ontology.drpawspaw.com/ADSO0000000071', 'Electrolyte Problem', []),
 ('https://ontology.drpawspaw.com/ADSO0000000019', 'Brain Cancer', []),
 ('https://ontology.drpawspaw.com/ADSO0000000028', 'Sneezing', []),
 ('https://ontology.drpawspaw.com/ADSO0000000046',
  'Abnormal Movement of Limbs',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000067', 'Liver Disease', []),
 ('https://ontology.drpawspaw.com/ADSO0000000052', 'Severe Lameness', []),
 ('https://ontology.drpawspaw.com/ADSO0000000009', 'Diarrhea', []),
 ('https://ontology.drpawspaw.com/ADSO0000000041',
  'High Fever',
  ['Increase Body Heat', 'High Temperature']),
 ('https://ontology.drpawspaw.com/ADSO0000000047', 'Holding the Leg up', []),
 ('https://ontology.drpawspaw.com/ADSO0000000030',
  'Loss of Appetite',
  ['Reduce Appetite']),
 ('https://ontology.drpawspaw.com/ADSO0000000014', 'Limb Swelling', []),
 ('https://ontology.drpawspaw.com/ADSO0000000099', 'Redness', []),
 ('https://ontology.drpawspaw.com/ADSO0000000091', 'Weakness', []),
 ('https://ontology.drpawspaw.com/ADSO0000000025', 'Low Body Temperature', []),
 ('https://ontology.drpawspaw.com/ADSO0000000073', 'Head Injury', []),
 ('https://ontology.drpawspaw.com/ADSO0000000072', 'Anemia', []),
 ('https://ontology.drpawspaw.com/ADSO0000000096',
  'Discharge from the Valva',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000068', 'Low Blood Sugar', []),
 ('https://ontology.drpawspaw.com/ADSO0000000093',
  'Breathing Difficulties',
  ['Breathing Problems', 'Irregular Breathing']),
 ('https://ontology.drpawspaw.com/ADSO0000000024',
  'Discomfort',
  ['Uncomfortable']),
 ('https://ontology.drpawspaw.com/ADSO0000000020', 'Dehydration', []),
 ('https://ontology.drpawspaw.com/ADSO0000000022', 'Rapid Heart Beat', []),
 ('https://ontology.drpawspaw.com/ADSO0000000031',
  'Thickening of nose and foot pads',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000066', 'Eating Poison', []),
 ('https://ontology.drpawspaw.com/ADSO0000000098',
  'Odor',
  ['Bad Smell', 'Unpleasant Smell']),
 ('https://ontology.drpawspaw.com/ADSO0000000021', 'Red Inflamed Tissue', []),
 ('https://ontology.drpawspaw.com/ADSO0000000039', 'Paralysis', []),
 ('https://ontology.drpawspaw.com/ADSO0000000037',
  'Head Tilt',
  ['Head Shaking']),
 ('https://ontology.drpawspaw.com/ADSO0000000044', 'Itchiness', []),
 ('https://ontology.drpawspaw.com/ADSO0000000036', 'Excessive Saliva', []),
 ('https://ontology.drpawspaw.com/ADSO0000000026',
  'Nasal Discharge',
  ['Nasal Whistling', 'Nasal Wheezing']),
 ('https://ontology.drpawspaw.com/ADSO0000000056', 'Thirsty', []),
 ('https://ontology.drpawspaw.com/ADSO0000000000', 'Encephalitis', []),
 ('https://ontology.drpawspaw.com/ADSO0000000032', 'Pneumonia', []),
 ('https://ontology.drpawspaw.com/ADSO0000000043',
  'Difficulty Exercising',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000079',
  'Pale Gums',
  ['White gum', 'Gray gum', 'Yellow gum']),
 ('https://ontology.drpawspaw.com/ADSO0000000074', 'Skin Scaling', []),
 ('https://ontology.drpawspaw.com/ADSO0000000095',
  'Popping sound on bones',
  []),
 ('https://ontology.drpawspaw.com/ADSO0000000063', 'Alopecia', ['Hair Loss']),
 ('https://ontology.drpawspaw.com/ADSO0000000064', 'Increase Urination', []),
 ('https://ontology.drpawspaw.com/ADSO0000000049', 'Scrab Eyes', []),
 ('https://ontology.drpawspaw.com/ADSO0000000069', 'High Blood Sugar', []),
 ('https://ontology.drpawspaw.com/ADSO0000000055', 'Bruising', []),
 ('https://ontology.drpawspaw.com/ADSO0000000061', 'Fatigue', []),
 ('https://ontology.drpawspaw.com/ADSO0000000042', 'Running Nose', []),
 ('https://ontology.drpawspaw.com/ADSO0000000012', 'Stroke', []),
 ('https://ontology.drpawspaw.com/ADSO0000000015',
  'Abnormal Pain',
  ['Heavy Pain', 'Severe Pain']),
 ('https://ontology.drpawspaw.com/ADSO0000000062', 'Appetite Changes', []),
 ('https://ontology.drpawspaw.com/ADSO0000000060', 'Frequent Paning', []),
 ('https://ontology.drpawspaw.com/ADSO0000000051', 'Inability to Walk', []),
 ('https://ontology.drpawspaw.com/ADSO0000000033', 'Skin Sores', [])]

In [ ]:
sympsyn[0][1]

'Bloated Tummy'

In [12]:
# Define more synonyms with the help of NLTK WordNet
from nltk.corpus import wordnet

def generate_synonyms(uri, keyword, syns):
    for synonym in wordnet.synsets(keyword):
        for item in synonym.lemmas():
            if keyword != synonym.name() and len(synonym.lemma_names()) > 1:
                syns.append(item.name())
    return (uri, keyword, syns)

In [15]:
for idx, (uri, keyword, syns) in enumerate(sympsyn):
    sympsyn[idx] = generate_synonyms(uri, keyword, syns)

In [16]:
sympsyn[0]

('https://ontology.drpawspaw.com/ADSO0000000059', 'Bloated Tummy', [])

In [17]:
expanded_symp = []

def is_exist(keyword, collection):
    for idx,word,syns in collection:
        if keyword == word:
            return True

for idx,word,syns in sympsyn:
    for s in syns:
        if not is_exist(s, sympsyn):
            expanded_symp.append((uri, s))
    if not is_exist(word, sympsyn):
        expanded_symp.append((uri, word))

In [18]:
len(expanded_symp)

216

In [19]:
expanded_symp[0]

('https://ontology.drpawspaw.com/ADSO0000000033', 'cough')

In [ ]:
def get_similarity(ne, idx, word):
    w1 = nlp(ne)
    w2 = nlp(word)
    return (idx, word, w1.similarity(w2))

nes = ["high body temperature"]

# for idx, (uri, word) in enumerate(expanded_symp):
#     expanded_symp[idx] = get_similarity(nes[0], uri, word)

In [ ]:
# sorted(expanded_symp, key=lambda x:x[2], reverse=True)

[('https://ontology.drpawspaw.com/ADSO0000000033',
  'Reduce body Weight',
  0.7052485903797944),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'flatness',
  0.607145956787246),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'dehydration',
  0.6067992004885375),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'dehydration',
  0.6067992004885375),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'desiccation',
  0.6016333427813714),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'desiccation',
  0.6016333427813714),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'evaporation',
  0.5833822244581235),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'inflammation',
  0.5548220513855556),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'Uncomfortable',
  0.5439616017908863),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'botheration',
  0.5326552050053484),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'looseness',
  0.52837917440410

In [ ]:
import pandas as pd
import openai, numpy as np
from openai.embeddings_utils import get_embedding, cosine_similarity

In [ ]:
response = openai.Embedding.create(
    input=["dog", "vehicle"],
    engine="text-similarity-davinci-001"
)

emb_1 = response["data"][0]["embedding"]
emb_2 = response["data"][1]["embedding"]

np.dot(emb_1, emb_2)

0.8092513169367387

In [ ]:
for idx, (uri, word) in enumerate(expanded_symp):
    response = openai.Embedding.create(
        input=[nes[0], word],
        engine="text-similarity-davinci-001"
    )
    emb_1 = response["data"][0]["embedding"]
    emb_2 = response["data"][1]["embedding"]
    expanded_symp[idx] = (uri, word, np.dot(emb_1, emb_2))

In [ ]:
sorted(expanded_symp, key=lambda x:x[2], reverse=True)

In [1]:
!pip install -U sentence-transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.0/86.0 KB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.8/5.8 MB 53.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 44.3 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 182.4/182.4 KB 18.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.6/7.6 MB 76.6 MB/s eta 0:00:00
  Created wheel for sentence-transformers: filename=sentence_transformers-2.2.2-py3-none-any.whl size=125938 sha256=756bb30872db2db58a767605e6e84210b25079d475ac75f8922415ef6d0bf9f0
  Stored in directory: /root/.cache/pip/wheels/5e/6f/8c/d88aec621f3f542d26fac0342bef5e693335d125f4e54aeffe
Successfully built sentence-transformers


In [2]:
!pip install torch --upgrade

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╸ 887.4/887.4 MB 51.5 MB/s eta 0:00:01tcmalloc: large alloc 1109270528 bytes == 0x3818e000 @  0x7fd975c8b615 0x5d6f4c 0x51edd1 0x51ef5b 0x4f750a 0x4997a2 0x55cd91 0x5d8941 0x4997a2 0x55cd91 0x5d8941 0x4997a2 0x55cd91 0x5d8941 0x4997a2 0x55cd91 0x5d8941 0x4997a2 0x55cd91 0x5d8941 0x4997a2 0x5d8868 0x4997a2 0x55cd91 0x5d8941 0x49abe4 0x55cd91 0x5d8941 0x4997a2 0x55cd91 0x5d8941
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 887.4/887.4 MB 1.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.0/21.0 MB 50.4 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 849.3/849.3 KB 30.8 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 317.1/317.1 MB 4.9 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 557.1/557.1 MB 3.0 MB/s eta 0:00:00
  Attempting uninstall: torch
    Found existing installation: torch 1.13.0

In [3]:
import torch.utils.checkpoint

In [4]:
!python -V

Python 3.8.16


In [5]:
from sentence_transformers import SentenceTransformer, util

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

Downloading:   0%|          | 0.00/1.18k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/190 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/10.6k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/612 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/116 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/39.3k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/112 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/466k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/350 [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/13.2k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/232k [00:00<?, ?B/s]

Downloading:   0%|          | 0.00/349 [00:00<?, ?B/s]

In [20]:
#@title Default title text
sentences = ["fever", "high body temperate", "lethargy"]

#Compute embedding for both lists
embedding_1= model.encode(sentences[0], convert_to_tensor=True)
embedding_2 = model.encode(sentences[1], convert_to_tensor=True)
embedding_3 = model.encode(sentences[2], convert_to_tensor=True)

# Calculate cosine similarity
print(util.pytorch_cos_sim(embedding_1, embedding_2))
print(util.pytorch_cos_sim(embedding_1, embedding_3))
print(util.pytorch_cos_sim(embedding_2, embedding_3))

tensor([[0.3124]])
tensor([[0.1703]])
tensor([[0.1279]])


In [21]:
def get_similarity(ne, idx, word):
    embedding_1 = model.encode(ne, convert_to_tensor=True)
    embedding_2 = model.encode(word, convert_to_tensor=True)
    return (idx, word, util.pytorch_cos_sim(embedding_1, embedding_2))

nes = ["high body temperature"]

for idx, (uri, word) in enumerate(expanded_symp):
    expanded_symp[idx] = get_similarity(nes[0], uri, word)

In [22]:
expanded_symp[0]

('https://ontology.drpawspaw.com/ADSO0000000033', 'cough', tensor([[0.0980]]))

In [23]:
# Sort by the similarity and get top five words
sorted(expanded_symp, key=lambda x:x[2], reverse=True)[:5]

[('https://ontology.drpawspaw.com/ADSO0000000033',
  'High Temperature',
  tensor([[0.8265]])),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'Increase Body Heat',
  tensor([[0.6556]])),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'feverishness',
  tensor([[0.4568]])),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'fever',
  tensor([[0.4186]])),
 ('https://ontology.drpawspaw.com/ADSO0000000033',
  'Reduce body Weight',
  tensor([[0.3238]]))]

In [1]:
!git commit -m "Complete the initial implementation of text-similarity"

fatal: not a git repository (or any of the parent directories): .git
